(* Polyglot v0.0.5 Grammar Specification *)
(* Extended Backus-Naur Form (EBNF) *)
(* Last Updated: 2026-01-04 *)

(* ============================================================================ *)
(* PROGRAM STRUCTURE *)
(* ============================================================================ *)

Program = PackageBlock, { EnumBlock | PipelineBlock } ;

PackageBlock = "{@}", PackageIdentifier, "{x}", Newlines ;

PackageIdentifier = "@", ScopeType, ":", PackageName, ":", Version ;

ScopeType = "Local" | "Shared" | "Public" ;

PackageName = Identifier, { "::", Identifier } ;

Version = Digit, { Digit }, ".", Digit, { Digit }, ".", Digit, { Digit }, ".", Digit, { Digit } ;

(* ============================================================================ *)
(* ENUM DEFINITIONS *)
(* ============================================================================ *)

EnumBlock = "{#}", EnumSignature, Newlines,
            [ AliasMarker, Newlines ],
            { SerialLoadBlock | FieldDef },
            "{x}", Newlines ;

EnumSignature = UserEnum, [ SchemaReference ] ;

UserEnum = "#", EnumPath ;

SchemaReference = "-", SchemaName ;

AliasMarker = "[A]", UserEnum ;

SerialLoadBlock = "[s]", "<<", Pipeline, Newlines,
                  { SerialFieldMapping },
                  "[s][!]", ErrorPattern ;

SerialFieldMapping = "[.]", Field, ":", Type, "<<", SerialPath, Newlines ;

SerialPath = ".", Identifier, { ".", Identifier } ;

FieldDef = "[.]", Field, ":", Type, [ "<<", Expression ], Newlines ;

Field = ".", Identifier ;

(* ============================================================================ *)
(* PIPELINE DEFINITIONS *)
(* ============================================================================ *)

PipelineBlock = "{|}", PipelineSignature, Newlines,
                [ MetadataBlock ],
                [ TriggerBlock ],
                [ InputBlock ],
                [ OutputBlock ],
                { WrapperBlock },
                { ExecutionStatement },
                "{x}", Newlines ;

PipelineSignature = "|", PipelineName ;

PipelineName = Identifier, { ".", Identifier } ;

(* ============================================================================ *)
(* TRIGGERS *)
(* ============================================================================ *)

TriggerBlock = "[t]", TriggerPipeline, [ StringLiteral ], Newlines,
               { TriggerIO } ;

TriggerPipeline = "|T.", TriggerType, [ ".", TriggerSubtype ] ;

TriggerType = "Cli" | "Cron" | "Interval" | "Folder" | "Calendar" | "HTTP" ;

TriggerIO = " | ", ( TriggerInput | TriggerOutput ), Newlines ;

TriggerInput = "<", ParamName, ":", Type, "<<", Expression ;

TriggerOutput = ">", ParamName, ":", Type, ">>", InputReference ;

InputReference = "<", Identifier ;

(* ============================================================================ *)
(* INPUTS & OUTPUTS *)
(* ============================================================================ *)

InputBlock = "[<]", InputDef, Newlines, { "[<]", InputDef, Newlines } ;

InputDef = "<", ParamName, [ "#", EnumType ], [ ":", Type ], [ "<<", Expression ] ;

OutputBlock = "[>]", OutputDef, Newlines, { "[>]", OutputDef, Newlines } ;

OutputDef = ">", ParamName, [ "#", EnumType ], [ ":", Type ],
            [ Newlines, { SubField } ] ;

SubField = "[.]", Field, ":", Type, "<<", Expression, Newlines ;

ParamName = Identifier ;

EnumType = EnumPath ;

(* ============================================================================ *)
(* WRAPPERS *)
(* ============================================================================ *)

WrapperBlock = "[w]", WrapperPipeline, Newlines,
               { WrapperIO } ;

WrapperPipeline = "|W.", WrapperType, [ ".", WrapperSubtype ] ;

WrapperType = "RT" | "DB" | "HTTP" | "File" ;

WrapperIO = " | ", ( WrapperInput | WrapperOutput ), Newlines ;

WrapperInput = "<", ParamName, [ SchemaShorthand ], ":", Type, "<<", Expression ;

WrapperOutput = ">", ParamName, [ SchemaType ], ":", Type, ">>", Variable ;

SchemaShorthand = "-", SchemaName, "#", EnumAlias ;

SchemaType = "-", SchemaName ;

SchemaName = Identifier, { "-", Identifier } ;

(* ============================================================================ *)
(* EXECUTION STATEMENTS *)
(* ============================================================================ *)

ExecutionStatement = RunStatement
                   | ParallelLoop
                   | SequentialLoop
                   | ForkStatement
                   | BranchStatement
                   | PackStatement ;

(* Run Statement *)
RunStatement = "[r]", ( VariableAssignment | PipelineCall ), Newlines ;

VariableAssignment = Variable, [ ":", Type ], AssignmentOp, Expression ;

AssignmentOp = "<<" | "<~" | ">>" | "~>" ;

(* Pipeline Call *)
PipelineCall = [ Variable, AssignmentOp ], Pipeline, Newlines,
               { PipelineIO },
               [ ErrorBlock ] ;

Pipeline = "|", PipelinePath, [ StringLiteral ] ;

PipelinePath = [ Namespace, "." ], PipelineName ;

Namespace = "U" | "RT" | "DT" | "DB" | "HTTP" | "File" | "Array" | "Set" | Identifier ;

PipelineIO = " | ", ( PipelineInput | PipelineOutput ), Newlines ;

PipelineInput = "<", ParamName, [ DotPath ], ":", Type, "<<", Expression ;

PipelineOutput = ">", ParamName, [ DotPath ], ":", Type, ">>", Variable ;

DotPath = { ".", Identifier } ;

(* ============================================================================ *)
(* LOOPS *)
(* ============================================================================ *)

ParallelLoop = "[p]", UnpackExpression, Newlines,
               { LoopStatement },
               [ PackStatement ] ;

SequentialLoop = "[r]", UnpackExpression, Newlines,
                 { LoopStatement },
                 [ PackStatement ] ;

UnpackExpression = Expression, ">>", UnpackOperator ;

UnpackOperator = "~", UnpackType, [ ".", CollectionType ] ;

UnpackType = "ForEach" | "Zip" | "Iter" ;

CollectionType = "Array" | "Set" | "Serial" | "IndexedArray" | "IndexedSet" ;

LoopStatement = RunStatement | ForkStatement | BranchStatement | PackStatement ;

PackStatement = "[*]", PackOperator, Newlines,
                { PackIO } ;

PackOperator = "*", PackType, [ ".", PackSubtype ] ;

PackType = "Into" | "Aggregate" | "String" ;

PackSubtype = "Array" | "Set" | "Serial" | "Sum" | "Count" | "Max" | "Min" | "Average" | "Concat" | "Lines" ;

PackIO = " * ", ( PackInput | PackOutput ), Newlines ;

PackInput = "<", "item", [ DotPath ], ":", Type, "<<", Expression ;

PackOutput = ">", ( "array" | "set" | "serial" | "sum" | "count" | "max" | "min" | "average" | "result" ), ":", Type, ">>", Variable ;

(* ============================================================================ *)
(* CONTROL FLOW *)
(* ============================================================================ *)

ForkStatement = "[f]", Condition, Newlines,
                { ExecutionStatement },
                [ ForkStatement ] ;

Condition = ( "*?" ) | ( Expression, ComparisonOp, Expression ) ;

ComparisonOp = "?=" | "?>" | "?<" | "?>=" | "?<=" | "?!=" ;

BranchStatement = "[b]", Condition, Newlines,
                  { ExecutionStatement } ;

(* ============================================================================ *)
(* ERROR HANDLING *)
(* ============================================================================ *)

ErrorBlock = "[!]", ErrorPattern, Newlines,
             { ErrorStatement },
             [ "[!]", "*", Newlines, { ErrorStatement } ] ;

ErrorPattern = "!", ErrorType, [ ".", ErrorSubtype ] | "!*" ;

ErrorType = Identifier ;

ErrorSubtype = Identifier, { ".", Identifier } ;

ErrorStatement = RunStatement | OutputDef ;

(* ============================================================================ *)
(* CODE BLOCKS *)
(* ============================================================================ *)

CodeBlock = "[c]", CodeLine, Newlines, { "[c]", CodeLine, Newlines } ;

CodeLine = { Character | VariableInterpolation } ;

VariableInterpolation = "{$", Identifier, "}" ;

(* ============================================================================ *)
(* EXPRESSIONS *)
(* ============================================================================ *)

Expression = Literal
           | Variable
           | Pipeline
           | CollectionLiteral
           | EnumValue
           | FieldAccess
           | SpecialValue ;

Literal = StringLiteral | NumberLiteral | PathLiteral | BooleanLiteral ;

StringLiteral = '"', { Character }, '"' ;

NumberLiteral = [ "-" ], Digit, { Digit }, [ ".", Digit, { Digit } ] ;

PathLiteral = "\\", { PathComponent, "\" }, [ FileName ] ;

PathComponent = Identifier ;

FileName = Identifier, [ ".", Identifier ] ;

BooleanLiteral = ReservedEnum ;

Variable = "$", Identifier, [ ".", Identifier ] ;

CollectionLiteral = ArrayLiteral | SetLiteral | SerialLiteral ;

ArrayLiteral = "(", [ Expression, { ",", Expression } ], ")" ;

SetLiteral = "{", [ Expression, { ",", Expression } ], "}" ;

SerialLiteral = "{:", [ SerialField, { ",", SerialField } ], "}"
              | "{", Newlines, { "[+]", SerialField, Newlines }, "[+]", "}", Newlines ;

SerialField = Field, ":", Expression ;

EnumValue = UserEnum, [ ".", EnumField ] | ReservedEnum ;

ReservedEnum = "-", EnumPath, [ "-", EnumField ] ;

EnumPath = Identifier, { ( "." | "-" ), Identifier } ;

EnumField = Identifier ;

FieldAccess = Variable, ".", Identifier, { ".", Identifier } ;

SpecialValue = SpecialPath | SpecialEnum ;

SpecialPath = "\\NoPath\" | "\\FileDir\" | "\\WorkDir\" ;

SpecialEnum = "-Input-None" | "-Success" | "-DT-Now" ;

(* ============================================================================ *)
(* TYPES *)
(* ============================================================================ *)

Type = PrimitiveType | CollectionType | EnumType | SchemaType | NativeType | ReservedType ;

PrimitiveType = "string" | "uint" | "int" | "float" | "bool" | "dt" | "path" | "serial" | "error" ;

CollectionType = "array", ".", Type
               | "set", ".", Type ;

NativeType = NativeLanguage, ".", NativeTypeName ;

NativeLanguage = "py" | "rust" | "js" ;

NativeTypeName = "str" | "int" | "float" | "bool" | "String" | "i32" | "u32" | "f64"
               | "string" | "number" | "boolean" ;

ReservedType = "-", TypeName ;

TypeName = Identifier, { "-", Identifier } ;

(* ============================================================================ *)
(* METADATA & COMMENTS *)
(* ============================================================================ *)

MetadataBlock = "[%]", MetadataKey, "<<", Expression, Newlines ;

MetadataKey = "%", Identifier ;

Comment = SingleLineComment | MultiLineComment ;

SingleLineComment = "%%", { Character }, Newline ;

MultiLineComment = "%{", { Character }, "}%" ;

(* ============================================================================ *)
(* LEXICAL ELEMENTS *)
(* ============================================================================ *)

Identifier = Letter, { Letter | Digit | "_" } ;

Letter = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M"
       | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
       | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m"
       | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" ;

Digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;

Character = Letter | Digit | SpecialChar ;

SpecialChar = "!" | "@" | "#" | "$" | "%" | "^" | "&" | "*" | "(" | ")" | "-" | "_" | "="
            | "+" | "[" | "]" | "{" | "}" | "\" | "|" | ";" | ":" | "'" | "\"" | "<" | ">"
            | "," | "." | "/" | "?" | "~" | "`" | " " | "\t" ;

Newline = "\n" | "\r\n" ;

Newlines = Newline, { Newline } ;

(* ============================================================================ *)
(* OPERATOR PRECEDENCE *)
(* ============================================================================ *)

(* Assignment Operators (left-to-right) *)
(*   <<  Pull final (highest precedence) *)
(*   <~  Pull default *)
(*   >>  Push final *)
(*   ~>  Push default *)

(* Comparison Operators (non-associative) *)
(*   ?=  Equal *)
(*   ?>  Greater than *)
(*   ?<  Less than *)
(*   ?>= Greater or equal *)
(*   ?<= Less or equal *)
(*   ?!= Not equal *)

(* Unpack Operator *)
(*   >>  Feed to unpack operator *)

(* Pack Operator *)
(*   *   Pack operator prefix *)

(* Error Operator *)
(*   !   Error type prefix *)

(* Reserved Enum Operator *)
(*   -   Reserved enum prefix *)

(* User Enum Operator *)
(*   #   User enum prefix *)

(* Field Operator *)
(*   .   Field access *)

(* ============================================================================ *)
(* SYNTAX RULES *)
(* ============================================================================ *)

(* 1. One expression per line rule: *)
(*    <indent(s)><Marker><One-expression> *)

(* 2. Field naming: *)
(*    - Compound fields: use underscores (field_name) *)
(*    - Reserved enum refs: use dashes (field-ReservedType) *)

(* 3. Indentation: *)
(*    - No indentation inside {} blocks *)
(*    - Loop bodies ARE indented *)
(*    - Pipeline I/O parameters: 1 space + " | " *)

(* 4. Newlines: *)
(*    - 3 blank lines before {} blocks (except {@} at file start) *)
(*    - 1 blank line before [] marker with pipeline call *)
(*    - No blank lines between consecutive I/O parameters *)

(* 5. Type annotations: *)
(*    - Always explicit for clarity *)
(*    - Use :dt not :datetime *)
(*    - Collection types include element type: array.uint *)

(* 6. Error handling: *)
(*    - Must be exhaustive *)
(*    - Use [!] !* for catch-all *)

(* 7. Variable lifecycle: *)
(*    - Maximum 2 pushes: one default <~, one final << *)
(*    - Default can be overridden *)
(*    - Final is immutable *)

(* 8. Comments: *)
(*    - %% for single-line *)
(*    - %{ }% for multi-line *)
(*    - Distinct from embedded code comments *)

(* 9. Reserved vs User enums: *)
(*    - Reserved: - prefix (stdlib) *)
(*    - User: # prefix (your code) *)

(* 10. Code blocks: *)
(*     - [c] recommended for multi-line code *)
(*     - [+] supported for compatibility *)
(*     - Variable interpolation: {$var} *)

(* ============================================================================ *)
(* END OF GRAMMAR *)
(* ============================================================================ *)
